TaskManager\Domain\Entity\Task:
    type: entity
    table: task

    id:
        id:
            type: task_id

    fields:
        title:
            type: string
            nullable: false
            length: 64
        dueDate:
            type: datetime_immutable
            nullable: false
        description:
            type: string
            nullable: true
        status:
            type: task_status
            nullable: false
            length: 16
